#+TITLE: Friday, 06/25/2021
** 08:20 setting up decentralized app
https://bitsofco.de/setting-up-a-decentralised-website/: really just claiming a wallet and space lol
come back to this though
** 17:25 on and off - focused work
identify with problem - deep focus is so hard to find. too many distractions
most effective people are the most effective at switching contexts - completely focusing on one thing and tuning everything else out. i can do this when i'm working, but whenever i'm not heavily invested it feels so difficult to invest, and when i am heavily invested work pervades the rest of my life. such a prolonged, forced intensity is not sustainable for a serious amount of time!

only focus for very short period of time - spending time appearing productive is bullshit and actually ends up wasting all of our time. half productive time spent appearing productive is actually incredibly cpounterproductive - you hight as well do something - anything! many believe it's not possible to get more than four hours of good writing done during a day - and after this the mind can't properly focus. 4 hours is so much time though!! you have to commit to being both totally on and totally off - never quite in between.

rest only comes from complete relaxation - not any of this halfassed shit. it's super difficult to keep things compartmentalized, but without pure attention it's so difficult to get anything done. pure attention is driving for ourselves, while distraction is just parting out that attention to many others.
** 18:02 always read and travel!
this writing isn't that good, but that's to be expected, because it's old and unseasoneed with experiences, though probably filled with much more literary knowledge than i am.
orwell wants us to be in love with every detail of our lives?
getting older means getting stingier with time - with whom and why - and extroversion is great but it's hard to spend lots of time with lots of others without accomodation? weird note. this definitely reads as someone yound and a bit pretentious, though with better taste in essay collections and writing than i. feels more like reading is searching for something in this essay - reading explicitly for self improvement or an escape rather than for reading itself. writing is hard!! like the explicit expression of her struggles. already synthesizing sources here, but the quotes feel scattered - not purposefUl.

new places to clear the head? try all of it! stay everywhere, get lost, hard to really talk about things you don't have the words for.

i like how perceptive i've become when reading essays like this - it means that i'm well read and understand myself well enough to both understand the lines and read through them. detecting immaturity is very important - with no meaning of immaturity other than the maturity of thoughts - as these observations inform just how much i've grown and learned about myself, even though i haven't been able to make substantial material progress. the ability to honestly criticize yourself may be the most valuable skill to have - as criticism means improvement, and being able to generate that criticism allows you to continue to generate improvement without a lot of external distraction. this could also be a sign of immaturity, though - as having lots of self criticism (honest, not deprecative) means that you haven't yet taken such criticisms to heart, so having no more criticism for yourself is a sign either that you can control yourself too little or that you focus on yourself too much. i have a headache. goodbye. ava used the liminal spaces cliche in this writing - and though i can relate to this thirst for experience no matter what the experience is, it seems silly to desire living on the brink of something rather than fully eperiencing it. we'll never find what we're looking for in each other!

just opened linkedin and saw a profile i'd seen before but who i have no real connection to. maybe it is time to quit socials
** 19:09 last writing from ava: we never learn (again)
protect good habits
quit before the bad habit digs in
hard work doesn't feel good at the time but it feels great later
stick with those who are emotionally healthy
fear of rejection is very expensive
always assert boundaries

we are both worthy of unconditional love - we didn't ask to be born so we should be cared for - but also full of flaws and dynamics that prove difficult to navigate. we build lives and burn them down, continuing to abandon the things we enjoy. nothing more potent than playing games you can't afford with people you don't deserve. that's the best line in this essay - an incredible one. we never learn
