#+TITLE: Tuesday, 06/01/2021
** 18:30 goals
no goals today
** diet
*** paris texas
interesting album - one song was fairly good, and i 'liked' it, but i don't have anything else to really comment. it's chill and just interesting enough to keep me listening.
*** knives out
incredibly well done movie - loved the bergeron sticker and the quick glampse of the mug.
*** last of twitter and instagram
i don't miss it. cool photography inspiration though. i'll keep posting regularly, but won't actively interact for awhile. the posting is incredibly important to me so i learn how to photograph, and to produce a good body of work, but actually using the platform is decidedly not. basically, i've found that feeds give me too little control over what i see, so i want to abolish feeds in favor of more intentional, organized content.
*** start using are.na
i need a way to organize the inspiration i keep around and are.na is the best way to do that. i kept from using it because it wasn't distributed and foss but that's stupid - it's pretty and it's the best tool for the job. i will use the platform to organize my inspirations until i develop a home grown solution in some way. i want the home grown solution to be spatiotemporal, though.
*** resist sharing
sharing content not made by me with others is unhealthy. it's cool to enjoy things but its not as fun to redirect, as if i'm taking credit for others credit for others credit for others and others. this will stop.
*** stupid clothing video
[[https://www.youtube.com/watch?v=1TMsxgWM-fw][src]]
i think i just wanted to watch this to satirize 'techwear' and keep up with the community, whatever that means. it's clear that being a part of this community, or pretending to, isn't really beneficial for me, because people who care about clothes above all else - buying clothes, not making them - are probably not interesting people to begin with. i love products but it's best to stay away from temptation.
