#+TITLE: Monday, 04/05/2021
** 10:23 first one in a long time
this is a good habit - I should really put some more time into it.
For now, though, some essay ideas/sketches:
*** American Hypocrisy - Public and Open, Private infrastructure and lives
housing and infrastructure mismanagement
we go big or go home, but going home is going big, buying large lots and properties, items in costco bulk.
we value independence, so instead of taking public transportation we purchase cars, cars that we have no right or ability to repair
we value the freedom to purchase property, property that prevents all of us from seeing the best views of the hollywood hills, keeps us from natural wonders

we're loud and proud, but purchase large amounts of private property

stockholm: all of the best views are public parks. hollywood: all the best views are from celebrity backyards. what is american exceptionalism but a desire to except all but the most privileged?
it's a classic gamer's dilemma - we don't know what's best for us, so we select things that arel ocally optimal in the short term and stick to the status quo rather thna long term
*** Finance is the wrong level of abstraction
Currency is a low level primitive; it was developed as a common abstraction to manage all transactions, standardizing trades - sheep for potatoes, tit for tat, etc. etc.
However, it wasn't designed to manage things we know we'll have to handle anyways - involuntary transactions. America's lowered many things to the financial level that shouldn't be, fundamentally - in a sane "first world" society, no member should have to worry about healthcare finances, for example. Taxes should happen automatically, as they do in many other countries; they should flow through the authority and to you, not given to you and taxed much later - then punished for not being adaquetely satisfied. We shouldn't have to worry about money in and of itself. We should worry about the institutions that mandate that we spend more time with money and less time on what matters. Unnecessary financial management is a real issue and, IMO, really does lead to a decreased quality of life, itnroducing additional anxiety, etc.
