#+TITLE: Wednesday, 06/23/2021
** 17:18 douglas coupland
popularized mcjob
can't recall why i had his profile open? looks like he's written some satirical critiques of tech work culture as an artist and designer.
ah, he wrote generation x and microserfs. seem like great books, might be worth looking into.

weird that he lived in tokyo. even five years is such a significant amount of time that it's impressive. i'm impressed by hopw much i can do on days that i'm motivated. maybe ii could change the world or something, or at the very least change my circumstances. betwene gymming and working out my brain surely my work can replace social media addiction and have a profound impact, at least on software.
** 17:21 exercise research
https://www.nytimes.com/2008/01/27/opinion/27taubes.html
tldr: cholesterol might just be a meme.
good cholesterol vs bad cholesterol may just be a joke with a history of discrimination against an asian high sodium diet - by association, surely soy sauce caused heart disease - without proper substantiation of investigation of latent variables?

low level - low density lipoproteins deemed a risk that could predict cardiovascular disease. the higher the amount of high density proteins, the lower the risk of heart disease; and, conversely, the concentration of low density lipoproteins proportional to the high density was considered a greater risk. ldl and hdl - associated with good chol and bad chol - became conflated with health, losing the idea that the causation might not be low and high cholesterol but the specific proteins themselves.

we don't even know if it's a major risk! large proportion of people who suffer heart attacks have low ldl cholesterol. this myth comes from assuming that saturated fat is bad - and association between saturated and ldl has created some feedback loop of terrible health, even though there is not compelling evidence that saturated fats cause heart disease.

article basically proposes that with all of the studies that have been done, there are a variety of latent variables that could better explain the issues iwth heart disease than ldl cholesterol has.
** 17:29 shulgin
https://en.wikipedia.org/wiki/Alexander_Shulgin
basically the godfather of acid and mdma research - tested and synthesized psychoactive drugs. raided frequently despite having a license to produce and test schedule one drugs, introduced the drug to psychologists across the nation and their powerful effects, and is suspected to have encouraged much of our mdma culture today. huge victim of the war on drugs via his research, worth learning much more about this man
