#+TITLE: Saturday, 04/10/2021
** 22:12 theory on distraction
this email was sent on march 2nd, but i've just found it now:
the more you can focus, the best you can get into deep work

but if you are not able to get into deep work, there is likely some distraction
- physical distraction. your environment is physically cluttered and has more visual interest. this prevents tou from concentrating on the task at hand and influences you to interact with other things
- temporal potential distraction. this occurs when you are placed on a time scale other than your own. if you know you have a looming deadline, you hesitate to begin or progress with a specific task because the initial investment may not be worth the time spent on the task.
- brain distraction. these are lingering thoughts, ideas and opportunities that distract from your current task. avoid these

always multitask - multitasking is good - but never in multiple ways. separate physical activity from mental. go on walks or runs with big questions in your head to come back with answers or progress. watch tv while doing pushups or situps. often abusing the distraction of a mental activity allows you to better perform the physical activity, and does not drain you nearly as much - though it certainly costs you some productivity in terms of physical fitness it will be net productive later, i think 
