#+TITLE: Friday, 06/25/2021
** 08:20 setting up decentralized app
https://bitsofco.de/setting-up-a-decentralised-website/: really just claiming a wallet and space lol
come back to this though
** 17:25 on and off - focused work
identify with problem - deep focus is so hard to find. too many distractions
most effective people are the most effective at switching contexts - completely focusing on one thing and tuning everything else out. i can do this when i'm working, but whenever i'm not heavily invested it feels so difficult to invest, and when i am heavily invested work pervades the rest of my life. such a prolonged, forced intensity is not sustainable for a serious amount of time!

only focus for very short period of time - spending time appearing productive is bullshit and actually ends up wasting all of our time. half productive time spent appearing productive is actually incredibly cpounterproductive - you hight as well do something - anything! many believe it's not possible to get more than four hours of good writing done during a day - and after this the mind can't properly focus. 4 hours is so much time though!! you have to commit to being both totally on and totally off - never quite in between.

rest only comes from complete relaxation - not any of this halfassed shit. it's super difficult to keep things compartmentalized, but without pure attention it's so difficult to get anything done. pure attention is driving for ourselves, while distraction is just parting out that attention to many others.
