#+TITLE: Thursday, 07/01/2021
** 14:05 making the best of it
i think the best way that someone can appreciate the world is to focus on the essentials. essentials: things everyone does to some extent but that some are passionate enough to master.

this seems far from the obscure, pretentious ideals of the academic culture i love and hate - endless abstraction feels unhealthy, as useful as it is for discussing complex ideas, as it prevents people from communicating with one another. learning shop language is fine, but often what should be accessible material is rendered inaccessible, and those newer to the field, to ideas, or resources are expected to take on the full burden of

here's what i am interested in focusing on:
- exercise and posture. everyone have to lift things and everyone can or has to walk or run. i'm interested in honing these skills - honing with my body, making daily tasks look effortless, and appearing structured and confident.
- writing (and reading?). everyone can, should, and/or must write - but few can eloquently express themselves in writing. i want to be able to. i want my writing to feel like me, and to hone myself to become more similar to my writing - or, at least, how i would like to portray myself, though i know i will never get there because accomplishing such a goal is tantamount to giving up on oneself. it's lovely to have something to strive for - truly.
- everyone takes photos. i want to take photos wellm to make them look nice, because photos show our real life to others better than anything else can and i want to be very good at that. recording the past for the future might be the most beneficial part of this
- cooking. everyone has to eat so becoming a great cook feels essential. making good, healthy and nutritious for yourself is incredibly worthwhile - and cooking and baking for others - to have someone else enjoy the results of your labor, to experience the joy of tasting something exquisite with them, is one of the greatest joys in life. baking too - baking might be the bset thing to do.

i'm sure there are more but they are currently escaping me. whatever the case i would like to be good at them. spending time on all of the things we /need/ - things that feel essential to human nature - feels incredibly valuable and satisfying.
** 21:36 personal advertisement
currently my profile pictures on each platform are a bit of a caricature of their respective sources; the twitter profile picture parodies the line used to convey replies and the instagram picture satirizes the private stories that many people use.

the first step is obtaining a consistent username across all platforms - this username doesn't have to be my real name, i don't think, and i'm okay with it being 'jakeisnt' - 'jakechvatal' doesn't quite feel like me. i'll have to figure out how to snag the username i prefer from others.

I like https://bitsofether.com/ and the way he has laid out all of his work, his value propositions, the people he has consulted for, etc. The testimonies, clear results and skillsets, client buzzwords, and the way the website is organized make for an excellent and easy to navigate interface.
