#+TITLE: Wednesday, 05/19/2021
** 11:56 some ideas from last night
*** website
where i list my opinions and rank my confidence in those opinions.
maybe use the sorter ecosystem thing to rank how highly i believe in the opinions
*** studying
how other people use the internet is probably my favorite hobby. it's fascinating to me how others choose to navigate the same spaces in such different ways - eventually accumulating experience to some peak, dropping off the internet entirely, becoming inactive, or flatlining and posting consistently forever. some become more abstract - focusing more and more on art projects and metatheories of the internet rather than concrete ideas and discussions - while others become much more serious and real, playing internet drama nad political games to try to accumulate social clout. some people share as little of their life as possible while others are incredibly social and active, exposing every detail of their lives. this deserves more research - how does internet addiction craft and shape the people who choose to actively contribute to it? how does it transform the attitudes of those who don't use the internet frequently - as by virtue of existing now everyone plays a part? it's unclear
