#+TITLE: Wednesday, 04/21/2021
** 16:32 good day! good hikes.
beautiful clear lake. thought about trying to release more writing via blog posts.
i want to write about whatever i'm interested in, which means technical topics sometimes, but i always
want to keep those entry level - capturing the fascination and my feelings /about/ the ideas without
tackling the meat of ideas.
this is important primarily because i want to make sure that even though i delve into these technical topics,
i am still a human and can talk to other humans - rather than dependent typers and semantics engineers - about
cool concepts that i enjoy and work on every day!


** 16:37 balance what you share and what you do
*** TODO this is a good blog post topic
*** etc
sharing is important, talking about what you love allows you to better communicate with those who share those interests and ideas. but talking impedes productivity! we also need to focus on making active progress on practical work, reading, gaining knowledge, etc, and the best way to do that is to actually do it rather than talk about it. balance these two things.
*** upgrade yourself
i did all of the easy things, the things that can be accomplished with little or brute force effort.
- mastered basic languages (js, python, functional style, etc...)
- basics in lots of categories (systems, programming languages, networking, setting up servers..)
- gained breadth of knowlege about programming, fashion, design, etc
- collected tons of aesthetic inspiration
now it's time for me to execute:
- deeper knowledge into programming languages to prepare to become a real researcher
- implement real applications, programs and games by myself or lead by myself with teams
- design clothes, fonts, and icons rather than just relying on references from others
- write more, build a following and share my interests with the world - publicly and accessibly!
