#+TITLE: Thursday, 06/24/2021
** 12:44 workout pro tips
*** 1
https://www.youtube.com/watch?app=desktop&v=TN9i9Ni0Xr4&feature=youtu.be might be a good series? would prefer a science guy to a trainer guy though

- enjoy training!! you will stick to your programs better. optimizing training program is fine, but focusing on sustainability requires focusing on personal health
- if you hate training might be good idea to min max time and training
- variety of training is fine rather than tracking the saem things every week, and it can add interest, but ensuring that you train the same things the whole time is incredibly beneficial
  + different exercises with the same core movements?
- most people in gym aren't pushing themselves hard enough!! don't leave most reps in the tank - 20% of trainees leaving 10 reps or more. have to push yourself to work out almost to failure
  + need to pack the stress on - don't leave any reps left in the tank at the end of the workout! that's what makes it a great workout!
- good guideline to level up on weight: if you can do two additional reps on the same exercise at that weight during two sets of that exercise for two weeks of working out. this means you're now far too comfortable with it. always push yourself!!!
- failure sets are great for isolation work but not for multiple joint movements that could impair other exercises and impact other training programs.
*** work 2
track number of workign sets. total work: about sets x reps x load
number of working sets - tough sets, without warmups - properly measure the number of working sets and should counrt towards the training volume
i was right about this guy being a total gym bro. he's spent ten minutes pointing at a graph that has volume on the x axis and gains on the y axis, explaining how you have to increase volume to increase gains over this hump, and what he's saying really doesn't line up with the graph at all, because it depicts gains decreasing at some level and he's advocating for people to push towards that. lots of acronyms i'm sure he's come up wiuth that dont mean anything................this is a bit of a joke.
i like the heuristics and numbers this guy provides but those are useful only because it's better to have some arbitrary heuristic to follow over nothing.
all really questions for measuring strength - though at end of the day all that matters is that you're applying appropriate effort from the outset.

this is what i love about the gym. effort you put in is effort you can seriously feel through this natural feedback solution.
coding has all of these strange side effects that cause physical fatigue instead of the coding - take eye strain, back pain and RSI for example!

*** conclusion
most workout advice on the internet is (as expectd) very poor. don't trust most or all of it. just try to work out every muscle group, push yourself to your limit, and feel good while doing so. that's the best way to build a strong foundation.
** 21:18 perceived effort where it counts
it's still not clear to me what i should do where, when and why. halfassing a neovim configuration provides no value to anyone, and it's unclear whether porting mine over is even worthwhile, but i feel like i have to carry on with it because it's practically done and it was on my list.

maybe sticking to a todo list despire a lack of motivation is very helpful for keeping my priorities straight, maybe it isn't. enthusiasm is hard to measure, track, and maintain, especially when working on projects with long time scales. it's often hard for me to see what the right decision, level of dedication or measure of effort is to invest into a task, so i will go all or nothing.

i think most of this is a result of being overstimulated - overexposed to loads of information i can't absorb at my own pace, because social networks set the pace instead. i should write more about how unhealthy social networks are but i feel like i've leveraged instagram very well - though what real connections has it lead to? regardless, i'll keep up my posting regimen to ensure that i'm holding myself accountable in terms of my creative goals - three posts a week no matter what.

there are too many places to go and too many things to do but i know i need to just focus on one or a few. i'm a good software engineer and i should continue to hone that skill. what else?
