#+TITLE: Tuesday, 06/08/2021
** 11:45
i dislike the writing of this driving course. i dislike writing with statistics, with improper and imprecise words, and writing with dialogue, though i tend to read a lot of writing with dialogue because most writing has dialogue. the flow of dialogue in comic books and manga in television is so much more natural because it captures depictions of people saying those things, whereas in writing the use of quotations to interrupt thoughts, emotions and feelings with, literally, "he said" and "she said" is so disruptive to the way things should be. writing should be endless and allow the reader to explore itself through it, but the quotations are significant in that they represent things that really happened, things that were really said, not just the abstractions and thoughts that live in our brains. even descriptions of events don't really capture the events, they capture what we think of them, just like statistics only capture a single point of view of a car accident and we have no choice but to choose which statistics to present, to tell an endless story in the news or to friends or through research by p-hacking, and all of these things in writing say more about the person describing the work or the methods by which the work is described than the work itself. description is beautiful basically.
