#+TITLE: Fitness

Fitness research and advice.

* "Best upper body workout"
[[https://www.youtube.com/watch?app=desktop&v=EuL017RWhT8&feature=youtu.be][Video with form]]

From video description:

I call this the upper body ripper.

3 minutes rest between sets. 12 in first set, 10 in second st, 8 in last set. Same ab amounts each.

Information here: http://sweatystartup.com/the-upper-bo...​

This is a workout I developed while in college and have found it to be an excellent way to quickly and efficiently build upper body definition and muscle. Make sure to accompany this workout with cardio on the other days of the week.

No long breaks. No catching your breath. You go through each workout of the set quickly and take only a 3 minute break between sets.

Equipment: Adjustable dumbbells and Perfect Pushups

Schedule: 2x per week

Directions: Go through this workout without putting the dumbbells down. 48 total reps with the dumbbells before the pushups and abs. First set 12 reps of each. Second set 10 reps of each. Third set 8 reps of each.

I usually use 30 lbs weights. You may need to start with 15 or 20 lbs or you may need 35 to 40 lbs. Use your judgement here.

One set equals:

12 curls
12 standing military press
12 upright rows
12 standing reverse flys
Put dumbbells down and go straight into:

15 perfect pushups (start with less if necessary)
15 middle crunches
15 left side crunches
15 right side crunches
12 middle crunches
12 left side crunches
12 right side crunches

I do the crunches using the Ab Ripper X style of in and outs on the middle and oblique v-ups on right and left side.

This is one set. I do 3 and I’m absolutely fried after the 15 minute workout. Your first week or two you should only do 2 sets and make sure to use light weight. If you are really sore take an extra day’s rest.
