#+TITLE: Generative Art

https://wiki.xxiivv.com/site/methascope.html
https://wiki.xxiivv.com/site/vast.html
https://wiki.xxiivv.com/site/lard_shader.html lard shader automation
https://wiki.xxiivv.com/site/brane.html digital fabrics
[[https://github.com/hundredrabbits/Ronin][experimental graphics terminal]]
https://wiki.xxiivv.com/site/moogle.html wireframe editor
[[https://ertdfgcvb.xyz/][studio for graphic design and art]]


https://constraint.systems/ [[file:text-editors.org][Text Editors]]
[[https://etch.constraint.systems/][Etch]]
[[https://mobile.twitter.com/alexandrosM/status/1314383329894912000][Alexandros Marinos on Twitter: &quot;Machines are making beautiful things without even trying to. We ask them to make something that optimizes for our requirements, they give us something back that looks surprisingly like nature. What is going on? A Thread https://t.co/809cWhc4ft&quot; / Twitter]]
[[https://futuristan.io][index | futuristan.io :: contemporary and digital art]]
[[https://hex.constraint.systems/][Hex]]
[[https://constraint.systems/mobile/][Constraint Systems]]
[[https://github.com/cloudhead/rx][pixel editor]]
https://en.m.wikipedia.org/wiki/Gray_code


http://subject.space/  lots of cool  projects motivated by space, maps, and tracking data around the world
https://blog.raeez.com/genesis/
https://iko.soy/dotrix drawing with vectors by touching!

https://drawabox.com/ learn to draw by starting a box!
 [[https://github.com/itsrainingmani/lsys][itsrainingmani/lsys: L-Systems: Interactive Fractal Generator]]
 [[https://github.com/urbit/sigil-js][urbit/sigil-js: ~4.2 billion default profile pics]]
https://nelari.us/ generate 3d buildings using node graphs,
also has generative art [[file:raytracing.org][Raytracing]] and is a[[file:blogs.org][Blogs]]

https://news.ycombinator.com/item?id=24111248

https://news.ycombinator.com/item?id=24091297 3d out of paper
https://eyeburfi-blog.tumblr.com/

* Tools for generative art

* helpful articles
[[https://tylerxhobbs.com/essays/2020/flow-fields][guide to flow fields]]
[[http://learningprocessing.com/][learning processing from first principles]]
[[https://www.dirtalleydesign.com/blogs/news/how-to-generative-art][good field overview of generative art resources]]

[[https://nannou.cc/][nannou: great low level multimedia toolkit]] [[file:rust.org][Rust]] 
[[http://www.generative-gestaltung.de/2/][another great looking processing book!]]
[[https://reas.com/][Casey REAS, creator of processing and one of the progenitors of generative art]]
[[https://tylerxhobbs.com/essays/2017/a-generative-approach-to-simulating-watercolor-paints][simulating watercolors with generative art]]
https://inconvergent.net/2016/shepherding-random-growth/: using generative organic methods for growth!

https://www.youtube.com/watch?v=me04ZrTJqWA : create generative art using image data. this looks absolutely incredible!
https://github.com/jasonwebb/morphogenesis-resources: archive of resources for the creation of form through code!
https://www.notion.so/Creative-coding-algorithms-techniques-c5550ef2f7574126bdc77b09ed76651b: notion database cataloguing tons of generative art techniques!
https://quazikb.github.io/WaveEq/index.html: a real time wave tracer technique

https://play.ertdfgcvb.xyz/abc.html#notes:technical a browser based live coding environment with live coding output; a tool and playground to play with ASCII, [[file:fonts.org][Fonts]], and otherwise.

https://alteredqualia.com/: brilliant image generation and generative art work. inspirational!

[[https://github.com/inconvergent/weir][a system for making generative algorithms]]; succeeds [[https://github.com/uvNikita/snek][snek]]
https://varun.ca/noises: an overview of noise in creative coding
