#+TITLE: Interior Design

- tags :: [[file:furniture.org][Furniture]], [[file:favorites.org][Items]]

[[https://www.benkuhn.net/lux/][your room can be as bright as the outdoors]]: brignening your room helps you stay more productive? the general[[file:blogs.org][Blogs]]  is good to follow as well

* TODO shelf idea
shelves that can detach from wall
use them as writing surface, desk or something
can mount them up on wall
thin sheets of metal that look like floating on wall :: minimal

* designer living philosophy
[[https://dribbble.com/stories/2019/01/24/freelance-designer-lilla-bardenova-on-creating-good-habits-and-finding-balance?utm_campaign=2021-02-17&utm_medium=email&utm_source=courtside-20210217][article]]
- full-time freelancing: turn any place into a working space! work from anywhere.
- live in a small studio with everything organized and functional. use a small desk to stay focused!
- work hard to build a concrete and strong routine. use external tracking tools. keep good habits and balance; this matters more than anything else. (I know this!)
