#+TITLE: Movies
* Recs
oldboy film korean
https://www.youtube.com/watch?v=3pT7gadYPso
https://en.wikipedia.org/wiki/Interstella_5555:_The_5tory_of_the_5ecret_5tar_5ystem
https://www.youtube.com/watch?app=desktop&feature=youtu.be&v=bzDjGvdvJXI
https://www.youtube.com/watch?app=desktop&v=3Q6Fzbgs_Lg
[[https://letterboxd.com/film/shiva-baby-2020/][Shiva Baby]]
[[https://www.justwatch.com/us/movie/metropolitan][Metropolitan]]
[[https://www.justwatch.com/us/movie/american-movie][American Movie]]

shingo_tamagawa (instagram?) Puparia movie

lady dynamite

perfect blue japanese thriller
paprika japanese thriller
a most violent year
happy as lazzaro
Roma
Trainspotting
Requiem for a dream
it's a sin: HBO max
promising young woman
minari
Sound of Metal!
some kind of heaven
the human factor?

dekalog: tv mini series

never rarely sometimes always
to your eternity! manga/anime?

palm springs
small axe: mangrove
bad education
first cow
Knives Out!!!!!!!!!!!!!

gunslinger girl
the melancholy of haruhi suzumiya

expelled from paradise
hellsing ultimate

manga cvn73 uss george
biomega!

books by haruki murakami!
the garden of sinners - japanese light novel
mind game- film - japanese
usagi drop

mushishi
spirited away
clannad: after story

ergo proxy: show
** bonnie!
play it again, sam: about a film critic obsessed with casablanca
annie hall
manhattan
weathering with you
** asdf
Arman: La Haine
Miracle on 34th street
Die Hard
American History X
the imitation game
** TODO [[https://www.youtube.com/watch?v=LETtcYGc__4][(249) Baraka (Ron Fricke, 1992) Documentary - YouTube]]

Captured On: [2020-09-14 Mon 20:50]
https://nibnalin.me/dust-nib/shadows-of-stained-glass.html
https://en.m.wikipedia.org/wiki/Drive_(2011_film)
[[https://www.criterion.com/][the criterion collection: classic movies]]
https://archive.org/details/CyberlifeShowOnOnliveTraveler1997
* Seen
** Akira
Worth all of the hype. A seminal cyberpunk fantasy with animation that still feels like it's from the future. There's no need for exposition because the story tells itself.
** Goodfellas
Great narrative -- clearly inspired movies like the wolf of wall street ans catch me if you can, among others.
** Monty Python and the Holy Grail
** Taxi Driver
** Pineapple Express
Stupid 'comedy' movie, no depth involved
** Office Space
Great movie, struck a bit close to home... definitely empathized with the main characters (aside from the hacking part).
** American Psycho
A bit scary that Bateman has taste so similar to mine... except for the psychopathic killer thing. Love his interior decor!
Can definitely see some examples of the type of person he will become (perhaps the misogyny and power tripping, but not the murder)
in some people I know today, which is a bit frightening given that he's intended to portray a caricature..
** nightcrawler - confirmed news is bad. very good character development
** into the wild
inspirational and novel. he lives a noble life - and though his decisions are stubborn, he learns so much along the way. highly recommend; personal journeys are the best kind of journey.
** silver linings playbook
- frustrating. how true is this? is it typical for people to spend most of their time talking about other people? maybe this is an oversight of mine.
** shutter Island
- predictable and forgettable
** Nomadland
simply stellar. dialogue is simplistic but sometimes this is fine + expected given the demographic. The emotions of the characters are complex enough.
** Mank
Basically nonsensical- though maybe I'm not aware enough of the history.
** feel good
excellent show. comedic realism. genuine same sex relationship. wish there were more but netflix business model bad.

* Record of a living being
https://cinemasojourns.com/2020/03/29/akira-kurosawas-record-of-a-living-being/
source
watch the film :: one of the first to directly address the fear of nuclear
holocaust and the implications of the atom bomb.  an introspective, cerebral
work regarding japan after the bomb and moving forward, away from fallout.
inspired by conversations with otuers regarding what may -- or may not be --
in store for us tomorrow, if tomorrow is in store at all.

