#+TITLE: Smess

[[https://github.com/jakeisnt/smess][smess repo]]

idea chat: it works like setting up meetings.
- what is your name?
- what is this meeting for?
launches you into meeting with topic being title. this works just like jitsi meet - you then share link to specific meeting for others to join the chat for the specific topic.

there are intentionally no fancy group features like discord or slack - this is purely for synchronously hashing out ideas. if multiple smess chats are open they are open in multiple tabs.

if a chat is not used for 24h it is automatically archived. nobody can chat in it anymore but all the links to ideas in the chat still work and new links can be created. this is to prevent endless hidden idea chats and to ensure that the chat stays on topic.
archived chat may have different ui that helps browse history in a better way. see the chatting with glue idea.

the motivation behind this is to create something spontaneous and synchronous for hashing out ideas - like you would with a video call or meeting - but because it's chat only everything is documented and traceable. inspired by synchronous meetings and mailing list archives - we want the longetivity and traceability of a mailing list archive with the real time impact of synchronous meetings and the sponteneity of a viral tweet (share idea from a chat on twitter - > implicitly invites others to chat - > 1 click signup to get into the chat room - no sign up concerns).

It's worth noting that `smess` does not intend to be a production-grade solution. Rather, it's a general framework to allow me to experiment with messaging ideas that have been suggested for a variety of platforms. It's designed to be temporary and incredibly configurable - an toolbox of ideas for an end user to try rather than a polished product to be deployed at scale.

* Inspiration
 https://cabal.chat/: a decentralized chat platform
