#+TITLE: Social
small scale social media

[[file:activitypub.org][ActivityPub]]
https://runyourown.social/#places-where-we-need-better-tech
[[https://lwn.net/Articles/741218/][federation in social networks: linux kernel blog]]
https://spiegelmock.com/2020/05/28/decentralizing-social-media/
[[https://github.com/rogeriochaves/feedless][a feedless social network]]

[[https://scuttlebutt.nz][scuttlebutt : the decentralized, social web. localized but distribued.]]
[[https://github.com/alexwennerberg/gourami][alexwennerberg/gourami: An intentionally small, community-focused decentralized microblogging service]]

[[https://kevq.uk/how-to-create-an-indieweb-profile/][How To Create An IndieWeb Profile - Kev Quirk]]
 [[https://tunemeet.com/][TuneMeet - Chat with people who are listening to the same song right now]]
https://joinwalrus.tv/

https://bp.io/avatar/ update twitter avatar on a site!
https://www.reddit.com/r/socialskills/comments/hyl9oh/200_interesting_questions_to_get_to_know_anyone/ questions to get to know anyone on a deeper level

https://gather.town/ 2d office spaces : )
* social networking on the internet
[[https://guzey.com/how-to-make-friends-over-the-internet/][source: how to make friends on the internet]]
- 90% of meeting people is reaching out. you must actively initiate conversations
- hang out in places where these other people are hanging out and do so frequently
- any platform with private messages allows you to make friends
- contact someone anytime you like something.
** using twitter
- respond to tweets on regular basis
- network with people they know and respond to their tweets as well
- ask local mutuals if they want to hang out
- having video calls could be almost as good as meeting in person?
- be someone people want to follow.
  - 1x per day
  - super low signal ot noise ratio
  - do not focus on retweeting
- create opportunities for discovery
  - talk to people. read their mentions. consistently bring value with replies
  - this happens even with people with large followings
** writing
- "networking for introverts"; "a serindipity vehicle"
- start blogging now and keep blogging. it's the best way to interact with others
** meeting people
[[http://benjaminreinhardt.com/networking-for-nerds/][networking for nerds]]
- create a mental model of yourself to become easy for anyone to meet
- if you have this projection, if you know how to market yourself, you know how to best network with others
- fuzzy projections are okay but they're harder to pinpoint.
- form this projection (about three pieces of information you'd like someone else to hold about you) - and market towards it.
- tell stories -- strong stories. narrow down your own story and use it in conversations with others. tell it on social media. repeat it at length.
- know your ask: the most impactful thing they can do to help you. this can be a local or a global goal; how can you best help other people? this makes it easiest for them to help you, gives them an action to reach back to you about, and keeps them from having to ask lots of clarifying questions. reduce the friction between you and them in terms of getting things done as soon as possible.
- pre meeting motions: scheduling, give as much information as possible, and be specific and accurate. refer back to the article all the time. do background information all of the time.
** concrete examples
- write: invite people to write you.
- reach out when you see someone you think it woul be interesting to meet
- ask people for intros and suggestions for people you should meet. do you know anyone i should meet and can you introduce me to them? do this asap. if you know a mutual, ask them for an introduction!
- browse reddit, twitter, etc. frequently with the intention of polling for these values.
- a big step is attending those research meetings i can be a part of
- traveling anywhere in the us is cheap. do /not/ be afraid to travel to network by any means.
* It is your responsibility to follow up
https://guzey.com/follow-up/
- follow up at max three times. follow up on a regular schedule. don't assume they will respond and keep the email around to remind others.
* Ideas not mattering is silly
- ideas may be cheap but there is never a guarantee of this. defeat your ideas. if they are not defeated, pursue them.
- good ideas are so obvious in retrospect, and they are only obvious in the moment if they do not have holes
- zero sum concepts are not worth it. ideas not mattering is just a marketing technique to assemble corporations
