#+TITLE: Talks

talks to listen to when i have time
https://www.youtube.com/watch?v=A65w-qoyTYg&app=desktop
https://www.youtube.com/watch?v=5QQdI3P7MdY&app=desktop
https://www.youtube.com/watch?v=VxINoKFm-S4&app=desktop
https://www.youtube.com/watch?v=nQ5He4gkCzc&app=desktop
https://www.youtube.com/watch?v=gui_SE8rJUM&app=desktop

* being human by being animal
https://www.youtube.com/watch?v=oG058g3f8Ik&app=desktop
removing animals of nay dignified cuteness; bojack horseman is pretty close
to this uncanny valley of creepy absurdism. the desire is not to make the
animals cute so much as lifelike and uncomfortable.

bojack as a horse ::  horse, long face, depression, juxtaposition of a
majestic animal as an alcoholic, etc. horse bredfor transportation but the
role no longer fulfulls the animal; could come from some broader interest in
horses
the main characters are drawn from domestic animals !
four legs good . two legs better . the control we have over domestic animals
is associated with the characters chosen for the show .

pushing the potential of animation to allow emotional states to hae an impact
on the world through cartoon absurdism ! the animalism enables them to reveal
the primal instincts of humans

blind recreation to create images that are readable.
diane. sometimes, life is a bitch; then, you keep living.
